/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xzr_perfmon_JniTools */

#ifndef _Included_xzr_perfmon_JniTools
#define _Included_xzr_perfmon_JniTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xzr_perfmon_JniTools
 * Method:    getcpufreq
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xzr_perfmon_JniTools_getcpufreq
  (JNIEnv *, jclass, jint);

/*
 * Class:     xzr_perfmon_JniTools
 * Method:    getadrenofreq
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xzr_perfmon_JniTools_getadrenofreq
  (JNIEnv *, jclass);

/*
 * Class:     xzr_perfmon_JniTools
 * Method:    getadrenoload
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xzr_perfmon_JniTools_getadrenoload
  (JNIEnv *, jclass);

/*
 * Class:     xzr_perfmon_JniTools
 * Method:    getmincpubw
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xzr_perfmon_JniTools_getmincpubw
  (JNIEnv *, jclass);

/*
 * Class:     xzr_perfmon_JniTools
 * Method:    getcpubw
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xzr_perfmon_JniTools_getcpubw
  (JNIEnv *, jclass);

/*
 * Class:     xzr_perfmon_JniTools
 * Method:    getm4m
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xzr_perfmon_JniTools_getm4m
  (JNIEnv *, jclass);

/*
 * Class:     xzr_perfmon_JniTools
 * Method:    getcpuload
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xzr_perfmon_JniTools_getcpuload
  (JNIEnv *, jclass, jint);

/*
 * Class:     xzr_perfmon_JniTools
 * Method:    checkcpuload
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_xzr_perfmon_JniTools_checkcpuload
  (JNIEnv *, jclass);

/*
 * Class:     xzr_perfmon_JniTools
 * Method:    getcpuonlinestatus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xzr_perfmon_JniTools_getcpuonlinestatus
  (JNIEnv *, jclass, jint);

/*
 * Class:     xzr_perfmon_JniTools
 * Method:    getmaxtemp
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xzr_perfmon_JniTools_getmaxtemp
  (JNIEnv *, jclass);

/*
 * Class:     xzr_perfmon_JniTools
 * Method:    getmemusage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xzr_perfmon_JniTools_getmemusage
  (JNIEnv *, jclass);

/*
 * Class:     xzr_perfmon_JniTools
 * Method:    getcurrent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xzr_perfmon_JniTools_getcurrent
  (JNIEnv *, jclass);

/*
 * Class:     xzr_perfmon_JniTools
 * Method:    getcpunum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xzr_perfmon_JniTools_getcpunum
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
